---

- name: Run a command on BIG-IP
  hosts: bigipa
  connection: local

  tasks:
    - name: show sys version
      bigip_command:
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        transport: rest
        commands:
          - show sys version
      delegate_to: localhost
      register: show

    - debug: 
        var: show.stdout_lines