---

- name: Run command on BIG-IP
  hosts: bigipa
  connection: local

  tasks:
    - name: tmsh show sys version
      bigip_command:
        commands: show sys version
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
      register: show

    - debug: 
        var: show.stdout_lines