---

- name: Remove single nodes
  hosts: "{{ bigip }}"
  connection: local

  tasks:
      - name: Remove nodes to the f5 demo pool
        bigip_pool_member:
            description: "f5demo_pool"
            name: "{{ item.name }}"
            password: "admin"
            pool: "f5demo_pool"
            port: "80"
            server: "bigipa"
            user: "admin"
            state: disabled
            partition: Common
            validate_certs: "no"
        delegate_to: localhost
        with_items:
            - name: "f5demo_node-5"
