---

- name: Create the DVWA VIP, pool, pool members and nodes
  hosts: bigipa
  connection: local

  tasks:
    - name: Create the DVWA pool
    bigip_pool:
        lb_method: "ratio_member"
        name: "dvwa_pool"
        password: "admin"
        server: "bigipa"
        slow_ramp_time: "120"
        user: "admin"
        validate_certs: "no"
    delegate_to: localhost

    - name: Create the DVWA node
    bigip_node:
        host: "10.1.20.17"
        name: "dvwa_node"
        password: "admin"
        server: "bigipa"
        user: "admin"
        validate_certs: "no"
    delegate_to: localhost

    - name: Add the DVWA node to pool
    bigip_pool_member:
        description: "dvwa_pool"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        password: "admin"
        pool: "dvwa_pool"
        port: "80"
        server: "bigipa"
        user: "admin"
        validate_certs: "no"
    delegate_to: localhost
    with_items:
        - host: "10.1.20.17"
            name: "dvwa_node"

    - name: Create the DVWA VIP
    bigip_virtual_server:
        description: "dvwa_vs"
        destination: "10.1.10.17"
        password: "admin"
        name: "dvwa_vs"
        pool: "dvwa_pool"
        port: "80"
        server: "bigipa"
        snat: "Automap"
        user: "admin"
        all_profiles:
            - "http"
            - "clientssl"
        validate_certs: "no"
    delegate_to: localhost