---

- name: Create the f5 Demo VIP, pool, pool members and nodes
  hosts: bigipa
  connection: local

  tasks:
      - name: Create the f5 demo pool
        bigip_pool:
            name: "f5demo_pool"
            user: "admin"
            password: "admin"
            server: "bigipa"
            slow_ramp_time: "120"
            lb_method: least-connections-node
        delegate_to: localhost

      - name: Create f5 demo node1
        bigip_node:
            host: "10.1.20.11"
            name: "f5demo_node-1"
            password: "admin"
            server: "bigipa"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create f5 demo node2
        bigip_node:
            host: "10.1.20.12"
            name: "f5demo_node-2"
            password: "admin"
            server: "bigipa"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create f5 demo node3
        bigip_node:
            host: "10.1.20.13"
            name: "f5demo_node-3"
            password: "admin"
            server: "bigipa"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create f5 demo node4
        bigip_node:
            host: "10.1.20.14"
            name: "f5demo_node-4"
            password: "admin"
            server: "bigipa"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create f5 demo node5
        bigip_node:
            host: "10.1.20.15"
            name: "f5demo_node-5"
            password: "admin"
            server: "bigipa"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Add nodes to the f5 demo pool
        bigip_pool_member:
            description: "f5demo_pool"
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            password: "admin"
            pool: "f5demo_pool"
            port: "80"
            server: "bigipa"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost
        with_items:
            - host: "10.1.20.11"
              name: "f5demo_node-1"
            - host: "10.1.20.12"
              name: "f5demo_node-2"
            - host: "10.1.20.13"
              name: "f5demo_node-3"
            - host: "10.1.20.14"
              name: "f5demo_node-4"
            - host: "10.1.20.15"
              name: "f5demo_node-5"

      - name: Create a VIP
        bigip_virtual_server:
            description: "f5demo_vs"
            destination: "10.1.10.10"
            password: "admin"
            name: "f5demo_vs"
            pool: "f5demo_pool"
            port: "80"
            server: "bigipa"
            snat: "Automap"
            user: "admin"
            all_profiles:
                - "http"
            validate_certs: "no"
        delegate_to: localhost
