---

- name: Create the DVWA VIP, pool, pool members and nodes
  hosts: bigipa
  connection: local

  tasks:
    - name: run show version on remote devices
      bigip_command:
        commands: show sys version
        server: "bigipa"
        password: "admin"
        user: "admin"
        validate_certs: "no"
      delegate_to: localhost

    - name: run show version and check to see if output contains BIG-IP
      bigip_command:
        commands: show sys version
        wait_for: result[0] contains BIG-IP
        server: "bigipa"
        password: "admin"
        user: "admin"
        validate_certs: "no"
      delegate_to: localhost

    - name: run multiple commands on remote nodes
      bigip_command:
        commands:
          - show sys version
          - list ltm virtual
        server: "bigipa"
        password: "admin"
        user: "admin"
        validate_certs: "no"
      delegate_to: localhost

    - name: run multiple commands and evaluate the output
      bigip_command:
        commands:
          - show sys version
          - list ltm virtual
        wait_for:
          - result[0] contains BIG-IP
          - result[1] contains vs
        server: "bigipa"
        password: "admin"
        user: "admin"
        validate_certs: "no"
      delegate_to: localhost

    - name: tmsh prefixes will automatically be handled
      bigip_command:
        commands:
          - show sys version
          - tmsh list ltm virtual
        server: "bigipa"
        password: "admin"
        user: "admin"
        validate_certs: "no"
      delegate_to: localhost