- name: Create a sync-only device group
  bigip_device_group:
      name: "foo-group"
      password: "secret"
      server: "lb.mydomain.com"
      state: "present"
      user: "admin"
  delegate_to: localhost

- name: Create a sync-only device group with auto-sync enabled
  bigip_device_group:
      name: "foo-group"
      auto_sync: "yes"
      password: "secret"
      server: "lb.mydomain.com"
      state: "present"
      user: "admin"
  delegate_to: localhost