- name: Use a file lookup to import key
  bigip_ssl_key:
      name: "key-name"
      server: "lb.mydomain.com"
      user: "admin"
      password: "secret"
      state: "present"
      content: "{{ lookup('file', '/path/to/key.key') }}"
  delegate_to: localhost

- name: Delete key
  bigip_ssl_key:
      name: "key-name"
      server: "lb.mydomain.com"
      user: "admin"
      password: "secret"
      state: "absent"
  delegate_to: localhost