- name: Create TCP Echo Monitor
  bigip_monitor_tcp_echo:
      state: "present"
      server: "lb.mydomain.com"
      user: "admin"
      ip: 10.10.10.10
      password: "secret"
      name: "my_tcp_monitor"
  delegate_to: localhost

- name: Remove TCP Echo Monitor
  bigip_monitor_tcp_echo:
      state: "absent"
      server: "lb.mydomain.com"
      user: "admin"
      password: "secret"
      name: "my_tcp_monitor"
  delegate_to: localhost