- name: Create a GTM pool
  bigip_gtm_pool:
      server: "lb.mydomain.com"
      user: "admin"
      password: "secret"
      name: "my_pool"
  delegate_to: localhost

- name: Disable pool
  bigip_gtm_pool:
      server: "lb.mydomain.com"
      user: "admin"
      password: "secret"
      state: "disabled"
      name: "my_pool"
  delegate_to: localhost