- name: Add AppSvcs Integration to iWorkflow
  iworkflow_iapp_template:
      device: "my-bigip-1"
      template_content: "{{ lookup('file', 'appsvcs_integration_v2.0_001.tmpl') }}"
      password: "secret"
      server: "lb.mydomain.com"
      state: "present"
      user: "admin"
  delegate_to: localhost

- name: Remove AppSvcs Integration from iWorkflow
  iworkflow_iapp_template:
      name: "appsvcs_integration_v2.0_001"
      password: "secret"
      server: "lb.mydomain.com"
      state: "present"
      user: "admin"
  delegate_to: localhost