---

- name: Run command on BIG-IP
  hosts: bigipa
  connection: local
  
  tasks:
    - name: tmsh show sys version
      bigip_command:
        server: "{{ inventory_hostname }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        commands: 
          - show sys version
          - list ltm virtual
      delegate_to: localhost
      register: tmsh

    - debug: 
        var: tmsh.stdout_lines