---

- name: Create the GTM server
  hosts: "{{ bigip }}"
  connection: local

  tasks:
    - name: Create GTM server "{{ gtmServer }}"
      bigip_gtm_server:
        server: "{{ bigip }}"
        user: "{{ username }}"
        password: "{{ password }}"
        name: "{{ gtmServer}}"
        datacenter: "{{ gtmDC }}"
        product: bigip
        link_discovery: disabled
        virtual_server_discovery: disabled
        devices:
          - {'name': 'server_1', 'address': '1.1.1.1'}
          - {'name': 'server_2', 'address': '2.2.2.1', 'translation':'192.168.2.1'}
        validate_certs: no
      delegate_to: localhost
