---

- name: Create GTM virtual server
  hosts: "{{ bigip }}"
  connection: local

  tasks:
    - name: Create virtual server "{{ vsName }}"
      bigip_gtm_virtual_server:
        server: "{{ bigip }}"
        user: "{{ username }}"
        password: "{{ password }}"
        virtual_server_name: "{{ vsName }}"
        virtual_server_server: "{{ vsServer }}"
        port: "{{ vsPort }}"
        state: present
        validate_certs: no
      delegate_to: localhost
