---

- name: GTM data center creation
  hosts: "{{ bigip }}"
  connection: local

  tasks:
    - name: Create GTM data center
      bigip_gtm_datacenter:
        server: "{{ bigip }}"
        user: "{{ username }}"
        password: "{{ password }}"
        name: "{{ gtmDC }}"
        location: "{{ location }}"
        validate_certs: no
      delegate_to: localhost

    - name: Create a GTM pool
      bigip_gtm_pool:
        server: "{{ bigip }}"
        user: "{{ username }}"
        password: "{{ password }}"
        name: "{{ gtmDC }}"_pool
        type: "a"
      delegate_to: localhost

    - name: Create GTM server "{{ gtmServer }}"
      bigip_gtm_server:
        server: "{{ bigip }}"
        user: "{{ username }}"
        password: "{{ password }}"
        name: "{{ gtmServer}}"
        datacenter: "{{ gtmDC }}"
        product: bigip
        link_discovery: disabled
        virtual_server_discovery: disabled
        devices:
          - {'ltm1': 'ltm_1', 'address': '1.1.1.1'}
          - {'ltm2': 'ltm_2', 'address': '2.2.2.1', 'translation':'192.168.2.1'}
        validate_certs: no
      delegate_to: localhost
